POST http://localhost:3003/api/orders/buyer/1
Content-Type: application/json

{
  "orders":[
    {"event_id": 1,
      "batches": [
        {
          "size_id": 36,
          "order_quantity": 2
        },
        {
          "size_id": 38,
          "order_quantity": 2
        }
      ]
    }
  ]
}