POST http://localhost:3003/api/orders/buyer/1
Content-Type: application/json

{
  "orders":[
    {"event_id": 1,
      "batches": [
        {
          "size_id": 42,
          "order_quantity": 2
        },
        {
          "size_id": 43,
          "order_quantity": 2
        }
      ]
    }
  ]
}