POST http://localhost:3003/api/products/1
Content-Type: application/json

{
  "product":{
    "name": "restTest",
    "organic": true,
    "sellers_id": 1,
    "type": "pc",
    "batch_quantity": 5,
    "description": "Tuotekuvaudfgds",
    "imageURL": "kuvasdfsdfalinsfdfffsdtrertertfdsfkki",
    "category": "Hedelmät & marjat",
    "deleteBeforeEvent": 2,
    "unit_price": 10,
    "vat": 24
  },
  "eventChoices": [1],
  "sizes": [{
    "price": 5,
    "quantity": 5,
    "unit": 1
  }]
}