POST http://localhost:3003/api/products/seller/1
Content-Type: application/json

{
  "product":{
    "name": "restTest",
    "organic": true,
    "sellers_id": 1,
    "type": "pc",
    "batch_quantity": 5,
    "description": "Tuotekuvaudfgds",
    "imageURL": "kuvalinsfdffkki",
    "category": "Hedelmät & marjat",
    "unit_price": 500,
    "vat": 24
  },
  "eventChoices": [1,2],
  "sizes": [{
    "quantity": 5,
    "unit": 1
  },
  {
    "quantity": 2,
    "unit": 1.5
  }]
}