PUT http://localhost:3003/api/users/76
Content-Type: application/json

{
  "seller_update": true,
  "reko_areas": [1,2],
  "seller_info": {
    "address": "Hämeentie 1",
    "name": "Terpan tila"
  },
  "user_info": {
    "firstname": "Touko",
    "lastname": "Puro",
    "phonenumber": "+358481237489275",
    "email": "puro.touko@gmail.com"

  }

}