PUT http://localhost:3003/api/users/76
Content-Type: application/json

{
  "seller_update": true,
  "reko_areas": {
    "delete": [2],
    "add": [2]
  },
  "seller_info": {
    "address": "Hämeentie 1",
    "name": "Terpan tila"
  }

}