PUT http://localhost:3003/api/products/50
Content-Type: application/json

{
  "product":{
    "name": "Sedän tuliset siivet",
    "organic": true,
    "sellers_id": 40,
    "type": "kg",
    "batch_quantity": 5,
    "description": "Tuotfdsfsekuvaudfgds",
    "imageURL": "kuvalinsfdfkki",
    "category": "Hedelmät & marjat",
    "unit_price": 69,
    "vat": 24
  },
  "eventChoices": [1],
  "sizes": [
    {
    "unit": 1,
    "quantity": 1
    }
  ]
}