PUT http://localhost:3003/api/users/1
Content-Type: application/json

{
  "seller_update": true,
  "reko_areas": {
    "delete": [3,1],
    "add": [1,5,4]
  },
  "seller_info": {
    "name": "Farmi :)",
    "homepage": "www.korhonen.fi",
    "address": "Mannerheimintie 3",
    "zipcode": "00101",
    "city": "Helsinki",
    "salesreport_check": true,
    "descriprtion": "I am pekka"
  },
  "user_info": {
    "firstname": "Pekka",
    "lastname": "Korhonen",
    "email": "pekkakorhonen@email.com",
    "phonenumber": "+358401234567"
  }
}