name: Deployment pipeline

on:
  push:
    branches: [main, staging]
  pull_request:
    branches: [main, staging]
    types: [opened, synchronize]

jobs:
  deployment_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "15.x"
      - name: install dependencies
        run: npm install
      - name: run tests
        run: npm run test
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: lint
        run: npm run fixlint
      - name: deploy
        if: ${{ github.event_name == 'push' && !contains(github.event.head_commit.message, '#skip') }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{ github.ref == 'refs/heads/main' && 'satoja-reko' || github.ref == 'refs/heads/staging' && 'satoja-staging' }} 
          heroku_email: "satojareko@gmail.com"
